export default {
    userdata: {},
    status: {
        loading: false,
        error: null,
    },
    Customers: [
        {
            name: "Lindsay Walton",
            address: "12 Jon Okon Street, Ilupeju",
            email: "lindsay.walton@example.com",
            phone_number: "08045334455",
            image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
            history: [
                {
                    id: 1,
                    orderNumber: "AT12PL270EFG",
                    productName: "65' LG 25PL1500 4K Smart Television",
                    downPayment: "₦12,500.00",
                    repayment: "₦4,000.00",
                    percentage: "20%",
                    duration: "6 Month",
                    date: "Jan 3, 2023",
                    verification: {
                        id: 1,
                        status: "awaiting",
                    },
                },
                {
                    id: 1,
                    orderNumber: "AT12PL270EFG",
                    productName: "65' LG 25PL1500 4K Smart Television",
                    downPayment: "₦12,500.00",
                    repayment: "₦4,000.00",
                    percentage: "20%",
                    duration: "6 Month",
                    date: "Jan 3, 2023",
                    verification: {
                        id: 1,
                        status: "failed",
                    },
                },
                {
                    id: 2,
                    orderNumber: "AT23TDF08EAA",
                    productName: "120L Thermocool Deep Freezer - VN2023",
                    downPayment: "₦45,500.00",
                    repayment: "₦12,500.00",
                    percentage: "40%",
                    duration: "3 Month",
                    date: "Dec 25, 2022",
                    verification: {
                        id: 1,
                        status: "successful",
                    },
                },
            ],
        },
        {
            name: "Lindsay Walton",
            address: "12 Jon Okon Street, Ilupeju",
            email: "lindsay.walton@example.com",
            phone_number: "09034441899",
            image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
            history: [
                {
                    id: 1,
                    orderNumber: "AT12PL270EFG",
                    productName: "65' LG 25PL1500 4K Smart Television",
                    downPayment: "₦12,500.00",
                    repayment: "₦4,000.00",
                    percentage: "20%",
                    duration: "6 Month",
                    date: "Jan 3, 2023",
                    verification: {
                        id: 1,
                        status: "awaiting",
                    },
                },
                {
                    id: 1,
                    orderNumber: "AT12PL270EFG",
                    productName: "65' LG 25PL1500 4K Smart Television",
                    downPayment: "₦12,500.00",
                    repayment: "₦4,000.00",
                    percentage: "20%",
                    duration: "6 Month",
                    date: "Jan 3, 2023",
                    verification: {
                        id: 1,
                        status: "successful",
                    },
                },
                {
                    id: 2,
                    orderNumber: "AT23TDF08EAA",
                    productName: "120L Thermocool Deep Freezer - VN2023",
                    downPayment: "₦45,500.00",
                    repayment: "₦12,500.00",
                    percentage: "40%",
                    duration: "3 Month",
                    date: "Dec 25, 2022",
                    verification: {
                        id: 1,
                        status: "failed",
                    },
                },
            ],
        },
        {
            name: "Lindsay Walton",
            address: "12 Jon Okon Street, Ilupeju",
            email: "lindsay.walton@example.com",
            phone_number: "09866554455",
            image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
            history: [
                {
                    id: 2,
                    orderNumber: "AT23TDF08EAA",
                    productName: "120L Thermocool Deep Freezer - VN2023",
                    downPayment: "₦45,500.00",
                    repayment: "₦12,500.00",
                    percentage: "40%",
                    duration: "3 Month",
                    date: "Dec 25, 2022",
                    verification: {
                        id: 1,
                        status: "failed",
                    },
                },
            ],
        },
        {
            name: "Lindsay Walton",
            address: "12 Jon Okon Street, Ilupeju",
            email: "lindsay.walton@example.com",
            phone_number: "07044554433",
            image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
            history: [
                {
                    id: 1,
                    orderNumber: "AT12PL270EFG",
                    productName: "65' LG 25PL1500 4K Smart Television",
                    downPayment: "₦12,500.00",
                    repayment: "₦4,000.00",
                    percentage: "20%",
                    duration: "6 Month",
                    date: "Jan 3, 2023",
                    verification: {
                        id: 1,
                        status: "awaiting",
                    },
                },
                {
                    id: 1,
                    orderNumber: "AT12PL270EFG",
                    productName: "65' LG 25PL1500 4K Smart Television",
                    downPayment: "₦12,500.00",
                    repayment: "₦4,000.00",
                    percentage: "20%",
                    duration: "6 Month",
                    date: "Jan 3, 2023",
                    verification: {
                        id: 1,
                        status: "successful",
                    },
                },
                {
                    id: 2,
                    orderNumber: "AT23TDF08EAA",
                    productName: "120L Thermocool Deep Freezer - VN2023",
                    downPayment: "₦45,500.00",
                    repayment: "₦12,500.00",
                    percentage: "40%",
                    duration: "3 Month",
                    date: "Dec 25, 2022",
                    verification: {
                        id: 1,
                        status: "failed",
                    },
                },
            ],
        },
    ],
    Customer:null,
    CustomerHistory: null
};
