name: Api Run tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: API Unit Tests
      run: |
        if echo $(git log --format=%B -n 1) | grep -q "Merge branch 'staging' into"; then
          echo "Skipping test"
        else
          echo "Running API tests"
        fi
