name: Run tests
on:
  pull_request:
    paths-ignore:
      - '**.js'
      - '**.vue'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          echo "No build required"
          echo $(github.event.head_commit.message)
