name: Run tests

on:
  pull_request:
    branches:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: npm ci

    - name: Print environment variables
      run: env

    - name: Run Tests
        if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'src/**/*.js') || contains(github.event.pull_request.changed_files, 'src/**/*.vue') && github.event.pull_request.base.ref != 'staging' }}
        run: npm test


