name: Run tests

on:
  pull_request:
    branches:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
      - '**.vue'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: npm ci

    - name: Print environment variables
      run: env

    - name: Run Tests
      run: |
        echo "Helloooo, kkkkkkkkk"
        echo $(git log --format=%B -n 1)
        echo ${{ join(github.event.commits.*.message) }}
        echo ${{ github.event.pull_request.head.ref }}
        echo ${{ github.event.pull_request.base.ref }}
        echo ${{ github.event.pull_request.changed_files }}
        echo ${{ contains(github.event.pull_request.changed_files, 'src/**/*.vue') }}
        echo ${{ github.base_ref }}
        echo ${{ github.event.pull_request.base.ref }}
        if ${{ !contains(run: echo $(git log --format=%B -n 1), "Merge branch 'staging' into") }}; then
          echo "I'm good to run"
        else
          echo "Nope stand still"
        fi
