name: Run tests

on:
  pull_request:
    branches:
    types: [opened, synchronize, reopened]
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: |
        if [ "${{ github.base_ref }}" = "refs/heads/staging" ]; then
          echo "Skipping tests"
        elif [ "${{ github.event_name }}" = "pull_request" ] && git diff --name-only "${{ github.event.pull_request.base.sha }}..${{ github.sha }}" | grep --quiet ".*\\.vue$"; then
          npm run test:unit
        else
          echo "No tests to run"
        fi


