name: Run tests

on:
  pull_request:
    branches:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
      - '**.vue'
      - '**.ts'

jobs:
  test:
    # if: "contains(github.event.head_commit.message, '[beaf]')"
    env:
      msg: ${{ github.event.head_commit.message }}
    if: "!contains(github.event.head_commit.message, 'SKIP CI')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      env:
        message: ${{ github.event.head_commit.message }}
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: npm ci

    - name: Print environment variables
      run: env

    - name: Debug
      run: |
        echo ${GITHUB_SHA}
        echo $(git log -1 --pretty=format:%H ${GITHUB_SHA}~1)
        echo $(git log -1 --pretty=format:%B ${GITHUB_SHA}

    - name: Run Tests
      run: |
        echo $(git log --format=%B -n 1)
        if echo $(git log --format=%B -n 1) | grep -q "Merge branch 'staging' into"; then
          echo "No test to run"
        else
          echo "Running tests"
          npm run test:unit
        fi
