name: Run tests

on:
  pull_request:
    branches:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
      - '**.vue'
      - '**.ts'

jobs:
  test:
    if: "!contains(github.event.pull_request.body, 'SKIP CI')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: |
        echo $(git log --format=%B -n 1)
        if echo $(git log --format=%B -n 1) | grep -q "Merge branch 'staging' into"; then
          echo "No test to run"
        else
          echo "Running tests"
          npm run test:unit
        fi
