name: Run tests

on:
  pull_request:
    branches:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
      - '**.vue'

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: npm ci

    - name: Print environment variables
      run: env

    - name: Print head git commit message
      id: get_head_commit_message
      run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"

    - name: Run Tests
      run: |
        echo "Helloooo, kkkkkkkkk"
        echo ${{ needs.check_skip_flags.outputs.head-commit-message }}
        echo ${{ github.event.head_commit.message }}
        echo ${{ github.event.pull_request.head.ref }}
        echo ${{ github.event.pull_request.base.ref }}
        echo ${{ github.event.pull_request.changed_files }}
        echo ${{ contains(github.event.pull_request.changed_files, 'src/**/*.vue') }}
        echo ${{ github.base_ref }}
        echo ${{ github.event.pull_request.base.ref }}
        if [ "${{ github.base_ref }}" = "refs/heads/staging" ]; then
          echo "Skipping tests"
        elif ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'src/**/*.js') || contains(github.event.pull_request.changed_files, 'src/**/*.vue') }}; then
          npm run test
        else
          echo "No tests to run"
        fi


