name: Run tests

on:
  pull_request:
    branches:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
      - '**.vue'
      - '**.t'

jobs:
  test:
    # if: "contains(github.event.head_commit.message, '[beaf]')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: npm ci

    - name: Print environment variables
      run: env

    - name: Debug
      run: |
        echo ${{github.event.pull_request.head.sha}}
        echo ${{github.event.head_commit.message}}
        echo $(git log -1 --pretty=format:%H HEAD~1)

    - name: Run Tests
      run: |
        echo $(git log --format=%B -n 1)
        if echo $(git log --format=%B -n 1) | grep -q "Merge branch 'staging' into"; then
          echo "No test to run"
        else
          echo "Running tests"
          npm run test:unit
        fi
