name: Unit Test Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  npm_unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Check if files have changed
        id: check_changes
        run: echo ::set-output name=files_changed::$(if [ "$(git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }} | grep -E '^()\/')" == "" ]; then echo "false"; else echo "true"; fi)
      - name: NPM Unit Tests for Unit
        if: steps.check_changes.outputs.files_changed == 'true' && github.head_ref != 'master' && !contains(github.event.pull_request.labels.*.name, 'no tests')
        run: |
          if [ "${{ github.event_name }}" != "pull_request" ] || [ "${{ github.event.action }}" != "closed" ] || [ "${{ github.event.pull_request.merged }}" != "true" ] || [ "${{ github.event.pull_request.base.ref }}" = "staging" ]; then echo "Skipping tests"; exit 0; fi
          npm install
          npm run test:unit
